# Generated by Django 3.2.3 on 2021-05-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('slug', models.SlugField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('correct_usages', models.IntegerField(default=0)),
            ],
        ),
    ]
